# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QDialog):
    def __init__(self, errormessage):
        super().__init__()
        
        self.errormessage = errormessage

        self.setWindowTitle('错误')
        self.resize(250, 160)

        self.textEdit = QtWidgets.QTextEdit(self)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(30, 30, 190, 60))
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setObjectName("textEdit")

        self.ConfirmButton = QtWidgets.QPushButton(self)
        self.ConfirmButton.setGeometry(QtCore.QRect(160, 100, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.ConfirmButton.setFont(font)
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.ConfirmButton.clicked.connect(self.close)

        self.retranslateUi(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.textEdit.setText(_translate("Form", self.errormessage))
        self.ConfirmButton.setText(_translate("Form", "确认"))
    


