# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(500, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setMinimumSize(QtCore.QSize(500, 70))
        self.textEdit.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.button_partilogin = QtWidgets.QPushButton(self.centralwidget)
        self.button_partilogin.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.button_partilogin.setFont(font)
        self.button_partilogin.setObjectName("button_partlogin")
        self.gridLayout.addWidget(self.button_partilogin, 3, 0, 1, 1)
        self.button_adminlogin = QtWidgets.QPushButton(self.centralwidget)
        self.button_adminlogin.setMinimumSize(QtCore.QSize(100, 50))
        self.button_adminlogin.setMaximumSize(QtCore.QSize(16777215, 16777215))

        self.button_adminlogin.setFont(font)
        self.button_adminlogin.setObjectName("button_adminlogin")
        self.gridLayout.addWidget(self.button_adminlogin, 2, 0, 1, 1)
        self.button_setaccount = QtWidgets.QPushButton(self.centralwidget)
        self.button_setaccount.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.button_setaccount.setFont(font)
        self.button_setaccount.setObjectName("button_setaccount")
        self.gridLayout.addWidget(self.button_setaccount, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)


        ## connect

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Agency FB\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:14pt;\">欢迎来到Lab Management系统</span></p></body></html>"))
        self.button_partilogin.setText(_translate("MainWindow", "受试者登录"))
        self.button_adminlogin.setText(_translate("MainWindow", "管理员登录"))
        self.button_setaccount.setText(_translate("MainWindow", "管理员账户管理"))
    


