# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QDialog):
    def __init__(self, reminder = None):
        super().__init__()
        if reminder is None:
            self.setWindowTitle('请登录管理员账号')
        else:
            self.setWindowTitle(reminder)
            
        self.resize(230, 170)

        self.textEdit_1 = QtWidgets.QTextEdit(self)
        self.textEdit_1.setEnabled(False)
        self.textEdit_1.setGeometry(QtCore.QRect(30, 30, 50, 30))
        self.textEdit_1.setUndoRedoEnabled(False)
        self.textEdit_1.setObjectName("textEdit_1")

        self.textEdit_2 = QtWidgets.QTextEdit(self)
        self.textEdit_2.setEnabled(False)
        self.textEdit_2.setGeometry(QtCore.QRect(30, 70, 50, 30))
        self.textEdit_2.setUndoRedoEnabled(False)
        self.textEdit_2.setObjectName("textEdit_2")
       
        self.IdText = QtWidgets.QTextEdit(self)
        self.IdText.setGeometry(QtCore.QRect(100, 30, 100, 30))
        self.IdText.setObjectName("IdText")
        
        self.PasswordText = QtWidgets.QTextEdit(self)
        self.PasswordText.setGeometry(QtCore.QRect(100, 70, 100, 30))
        self.PasswordText.setObjectName("PasswordText")
       
        self.button_login = QtWidgets.QPushButton(self)
        self.button_login.setGeometry(QtCore.QRect(65, 110, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.button_login.setFont(font)
        self.button_login.setObjectName("button_login")

        self.retranslateUi()
        self.info = None

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        
        self.button_login.setText(_translate("Form", "登录"))
        self.textEdit_1.setText(_translate("Form", "ID："))
        self.textEdit_2.setText(_translate("Form", "密码："))

    def get_info(self):
        self.info = [self.IdText.toPlainText(), self.PasswordText.toPlainText()]
