# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QDialog):
    def __init__(self, admin_info):
        super().__init__()
        self.admin_info = admin_info
        self.setWindowTitle("欢迎您，{}！请输入您的新密码".format(self.admin_info[1]))
        self.resize(300, 170)

        self.textEdit_1 = QtWidgets.QTextEdit(self)
        self.textEdit_1.setEnabled(False)
        self.textEdit_1.setGeometry(QtCore.QRect(30, 30, 100, 30))
        self.textEdit_1.setUndoRedoEnabled(False)
        self.textEdit_1.setObjectName("textEdit_1")

        self.textEdit_2 = QtWidgets.QTextEdit(self)
        self.textEdit_2.setEnabled(False)
        self.textEdit_2.setGeometry(QtCore.QRect(30, 70, 100, 30))
        self.textEdit_2.setUndoRedoEnabled(False)
        self.textEdit_2.setObjectName("textEdit_2")
       
        self.PasswordText = QtWidgets.QTextEdit(self)
        self.PasswordText.setGeometry(QtCore.QRect(160, 30, 110, 30))
        self.PasswordText.setObjectName("PasswordText")
        
        self.PasswordText2 = QtWidgets.QTextEdit(self)
        self.PasswordText2.setGeometry(QtCore.QRect(160, 70, 110, 30))
        self.PasswordText2.setObjectName("PasswordText2")
       
        self.button_confirm = QtWidgets.QPushButton(self)
        self.button_confirm.setGeometry(QtCore.QRect(100, 110, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.button_confirm.setFont(font)
        self.button_confirm.setObjectName("button_confirm")

        self.retranslateUi()
        self.info = None

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        
        self.button_confirm.setText(_translate("Form", "确定"))
        self.textEdit_1.setText(_translate("Form", "新密码："))
        self.textEdit_2.setText(_translate("Form", "再次输入："))

    def get_info(self):
        self.info = [self.PasswordText.toPlainText(), self.PasswordText2.toPlainText()]
