# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QDialog):
    def __init__(self, admin_info):
        super().__init__()
        self.admin_info = admin_info

        self.resize(520, 280)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setMinimumSize(QtCore.QSize(500, 70))
        self.textEdit.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.button_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.button_confirm.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.button_confirm.setFont(font)
        self.button_confirm.setObjectName("button_confirm")
        self.gridLayout.addWidget(self.button_confirm, 2, 0, 1, 1)
        self.button_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.button_cancel.setMinimumSize(QtCore.QSize(100, 50))
        self.button_cancel.setMaximumSize(QtCore.QSize(16777215, 16777215))

        self.button_cancel.setFont(font)
        self.button_cancel.setObjectName("button_cancel")
        self.gridLayout.addWidget(self.button_cancel, 3, 0, 1, 1)
        self.button_transfer = QtWidgets.QPushButton(self.centralwidget)
        self.button_transfer.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.button_transfer.setFont(font)
        self.button_transfer.setObjectName("button_transfer")
        self.gridLayout.addWidget(self.button_transfer, 4, 0, 1, 1)
        #self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)


        ## connect

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "删除管理员账户"))
        self.textEdit.setText(_translate("Form", "将删除账户{}-{}以及其负责的所有受试者记录，确认继续？".format(self.admin_info[0], self.admin_info[1])))
        self.button_confirm.setText(_translate("Form", "确认"))
        self.button_cancel.setText(_translate("Form", "取消"))
        self.button_transfer.setText(_translate("Form", "将受试者记录转移至另一个管理员账户"))
