# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, admin_name):
        self.admin_name = admin_name

        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(500, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setMinimumSize(QtCore.QSize(500, 70))
        self.textEdit.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.button_newaccount = QtWidgets.QPushButton(self.centralwidget)
        self.button_newaccount.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.button_newaccount.setFont(font)
        self.button_newaccount.setObjectName("button_newaccount")
        self.gridLayout.addWidget(self.button_newaccount, 3, 0, 1, 1)

        self.button_changepassword = QtWidgets.QPushButton(self.centralwidget)
        self.button_changepassword.setMinimumSize(QtCore.QSize(100, 50))
        self.button_changepassword.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_changepassword.setFont(font)
        self.button_changepassword.setObjectName("button_changepassword")
        self.gridLayout.addWidget(self.button_changepassword, 2, 0, 1, 1)

        self.button_delaccount = QtWidgets.QPushButton(self.centralwidget)
        self.button_delaccount.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.button_delaccount.setFont(font)
        self.button_delaccount.setObjectName("button_delaccount")
        self.gridLayout.addWidget(self.button_delaccount, 4, 0, 1, 1)

        self.button_logout = QtWidgets.QPushButton(self.centralwidget)
        self.button_logout.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.button_logout.setFont(font)
        self.button_logout.setObjectName("button_logout")
        self.gridLayout.addWidget(self.button_logout, 5, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)


        ## connect

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "欢迎您，{}".format(self.admin_name)))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Agency FB\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:14pt;\">请选择您要进行的操作</span></p></body></html>"))
        self.button_newaccount.setText(_translate("MainWindow", "新建管理员账号"))
        self.button_changepassword.setText(_translate("MainWindow", "修改密码"))
        self.button_delaccount.setText(_translate("MainWindow", "删除当前管理员账号"))
        self.button_logout.setText(_translate("MainWindow", "退出登录"))
    


